### ISSUE TITLE
How can i pass more than one env ?

### ISSUE THREAD

**Issue by naynivek** [garbetjie/terraform-google-cloud-run#5]
I tried this example:

  env = [{ key = "DB_HOST",value = var.database_dns_name },
        { key = "DB_PASS", value = var.schema_pass }]

But i got this error:
Cannot use a tuple value in for_each. An iterable collection is required.

**Comment by garbetjie** [comment]
@naynivek Could you confirm the module version & terraform version you're using? I remember receiving an error similar to this on one of the older versions. I'm currently using this module in production, and I'm not receiving this error.

Is there any way you're able to provide a sample usage of the module that replicates this issue (with sensitive values redacted/removed of course)? It would really help in trying to track down the issue.

**Comment by naynivek** [comment]
Hi, thanks for the answer!
My terraform is in v0.15.4
Your module is in v2.0.0

This is module config, it's working because i'm passing only one var in env, when i try more than one, i get the error.
```
module "cloud-run" {
  source = "garbetjie/cloud-run/google"
  version = "~> 2"

  name     = var.service_name
  image    = var.image
  location = var.location
  allow_public_access = true
  env = [{ key = "DB_HOST",value = var.database_dns_name}]

  vpc_access = { connector = var.vpc , egress = "private-ranges-only" }
  max_instances = 2
  min_instances = 0
  port = 80

}
```

**Comment by garbetjie** [comment]
Hmmm... Wrapping the `var.schema_pass` value in a `nonsensitive()` function call should help.

I'm not sure whether the issue could be caused by the fact that the env values are also displayed in the output, and Terraform is perhaps complaining about that? Could you try use `git@github.com:garbetjie/terraform-google-cloud-run?ref=test-sensitive-env` as the source for the module? I've added the `sensitive = true` attribute to the env output in that branch. That might help fix it. If it does, I'll update the docs to reflect this issue.

If it doesn't help, the `nonsensitive()` function call might help, and I'll try take another look when I have a moment.

**Comment by naynivek** [comment]
Yes, the nonsesitive() function worked for me!
Thanks a lot!
```
output "username" {
  description = "username"
  value       = google_sql_user.user.name
}

output "password" {
  description = "password"
  value       = nonsensitive(google_sql_user.user.password)
}

output "schema_name" {
  description = "schema name"
  value       = google_sql_database.schema.name
}
```
